name: first-gaga-action

on:
  workflow_dispatch:

jobs:
  first_job:
    name: get
    runs-on: ubuntu-latest
    steps:
    - name: s001
      env:
        x: 111
        y: 222
      run: |
        echo "get private env: $x,$y"
        echo "the username: ${{ inputs.username }}"
