name: first-gaga-action

on:
  workflow_call:
    inputs:
      username:
        description: 'A username passed from the caller workflow'
        default: 'mvpbang'
        required: false
        type: string

jobs:
  first_job:
    name: get
    runs-on: ubuntu-latest
    steps:
    - name: s001
      env:
        x: 111
        y: 222
      run: |
        echo "get private env: $x,$y"
        echo "the username: ${{ inputs.username }}"
